### ISSUE TITLE
Buy the man a beer +bug

### ISSUE THREAD

**Issue by 222craft** [H4vC/PoeHud#36]
I'm new around here, but I want to start by saying thanks with a beer, where can I do that H4vC?

Onto the Bug?:
Since the new patch came out (end of March 2015), I have had the app crash 2 dozen times in 5 days.  3 weeks prior to that, 3 crashes tops.
Circumstances: start PoE as normal, load up as normal. Everything works find but will hang with an error "unable to load.."(Ill try get exact error next time it happens).  Onscreen the HUD stays static and doesn't update further.  I can only close it by using task manager to end task.  If I start PoEHUD again, it works fine.

Suggestion:
I would really like to have the ability to configure different lists of items. each list can have it's own sound file it refers to and ideally a different border colour too?  The idea being rare currency/Uniques can have a special sound and crafting items or other less valuables can have a lesser sound?

Thank you for your efforts into PoE Hud, this makes the  game 100 times more enjoyable. Please keep up the good work!

Kind Regards,
2C

**Comment by H4vC** [comment]
The correct error would help tons, I can't take suggestions at the moment as I'm very occupied with real life stuff. I also do not take donations, I am sorry.

**Comment by H4vC** [comment]
Being implemented in game closed
