### ISSUE TITLE
Corrupted Area (Preload alert)

### ISSUE THREAD

**Issue by smad2005** [H4vC/PoeHud#41]
With "human_heart" not always shows "Corrupted Area".

**Comment by H4vC** [comment]
I don't think corrupted areas have any other specific preload ?

**Comment by smad2005** [comment]
was https://github.com/H4vC/PoeHud/commit/db9cd13665dc87a70fac1bbdd2ccc1c5eeecbbec

**Comment by H4vC** [comment]
Should we revert or try to find out whether there is a way to filter out master specific ones ?

**Comment by smad2005** [comment]
For now i don't know what to do (I haven't investigated it), I think the problem in that this is the "Particle" and not the texture.

**Comment by H4vC** [comment]
Made an attempted fix.

**Comment by smad2005** [comment]
thx

**Comment by smad2005** [comment]
checked 5 areas, 5 of 5, it works great!!! Thx again.

**Comment by H4vC** [comment]
Closing as it seems to be fixed.
No need to thank me really.
