### ISSUE TITLE
Is this safe to use? I remember Old PoEHud was detected

### ISSUE THREAD

**Issue by phurionxy** [H4vC/PoeHud#44]
Is this safe to use? I remember old PoE hud was detected. Concidering now that this doesnt using maphack and what not is it still detectable?

**Comment by H4vC** [comment]
Currently undetected, and i'll keep it that way for as long as I can you should make sure to check the ac thread on ownedcore, please do not open issues of this kind since it doesn't pertain to the poehud code but rather the AC.
