### ISSUE TITLE
Not an issue: How about remaining

### ISSUE THREAD

**Issue by konradmm** [H4vC/PoeHud#55]
More like a idea of feature.
Why not adding something like: "Remaining Monsters: 20+" on hud?
Pretty simple but i guess /remaining command is used MANY times...

**Comment by ghost** [comment]
"/remaining" is a command that has to be write into memory, highly detectable, fast ban.

**Comment by H4vC** [comment]
We cannot do this in a way that makes sense, since not all the mobs are loaded in only those around you and I personally won't have memory writing (to spam /remaining.) in this branch of the HUD. 
I'm closing this because we can't do any better than a simple macro would.
