### ISSUE TITLE
Menu button disappears, but Hud still working.

### ISSUE THREAD

**Issue by ZombieRexRider** [H4vC/PoeHud#56]
No idea how to replicate this. I've had it happen on two different computers (one low end, with lowest settings possible for PoE, and one on high). It just seems to happen the more I use the tool. The Hud still works, but I can't change the options at all because of the missing menu button. 

Will try for solutions, but looking for the cause is great. 

Solutions to try:
1. Restart computer - Done this a few times on the low end. Haven't on the high end. Low didn't work.
2. Re-download the tool
3. Changing graphic options

**Comment by ghost** [comment]
Try to press F12..., it's for show/hide Menu.

**Comment by ZombieRexRider** [comment]
Will do. Didn't know about that at all.

On the high end pc : 
Pressing F12 worked. There are instances where menu button is visible but unclickable.

On the low end pc (with small window screen):
Menu button seems to be offscreen. It's off to the left, with only a small fraction of the menu button visible.
