### ISSUE TITLE
PoE HuD overlay problem

### ISSUE THREAD

**Issue by twisteddominates** [H4vC/PoeHud#60]
Hello i am new to the HuD was trying to get this working last night. I have windows 8.1 and got the hud to come up but having a offset problem or something. The map will have x where mobs are and it is off. like i kill one and its way across the map that x goes away. says mobs are off the map etc. Also can not use the menu feature to turn things on or off. Went into the settings and tried to chance menu from false to true but that didn't help either. The hud is off screen and only way i can get it right is in 800 x 600. it will say everything on screen but map is still off for monsters, barrels, and drops do not light up. I a new to this thing, did use T hud for diablo 3 but about it not a tech savvy person. Computer is a Asus RoG G751 i7-4710HQ, 1TB HDD, 8 gig ram, nvidia geforce gfx 860m graphics and intel graphics. It's a laptop and idk what im doing wrong. I run HuD as admin. Any idea's to help me get thing working?

**Comment by H4vC** [comment]
be sure to set dpi to be at 100% win 8.1 isn't officially supported I can't offer much help try the forum thread, issue closed.

**Comment by twisteddominates** [comment]
Sorry if i posted in the wrong area, new to this, did not mean to throw up a red flag. That did fix my problem, had to good dsi and figure it out but thank you very much. Going to try and learn it now, seems awesome and will try to support when i get paid.

**Comment by H4vC** [comment]
No problems, there's no actual way to support development but feel free to post on the forums/etc.
