### ISSUE TITLE
Health Bar - 10% for Culling

### ISSUE THREAD

**Issue by sjau** [H4vC/PoeHud#65]
Hi there

I wonder if there's a way to alter the colour of the health bars when the mob is 10% or below so that you can switch to your culling strike/item rarity attack?

Especially on Unique mobs that would be a great help. Or maybe make some audio feedback when 10% is reached. In that case maybe only for rare and unique mobs.

**Comment by smad2005** [comment]
```
 "Health bar": {
    "Enable": true,
    "ShowInTown": true,
    "ShowES": true,
    "ShowIncrements": true,
    "ShowEnemies": true,

...
      "Under10Percent": "ffffffff",
```

"Under10Percent" property

**Comment by sjau** [comment]
I'll have to give that a try :) thx
