### ISSUE TITLE
Missing detection for Cartographer Box.

### ISSUE THREAD

**Issue by Greg36** [H4vC/PoeHud#70]
Today I was running Promenade 71lvl map, on the preload alert there was no carto box, but I it was present in the map.
Other preload alers work good.

I restarted the program, but it did not help.

**Comment by Greg36** [comment]
In Imperial Gardens it displays carto correctly. Dunno why it was not properly shown on the promenade map, maybe because it was rare box there.

**Comment by H4vC** [comment]
We don't deal with rarity, there must be an edge case where not all map data is read correctly I'll go look into it.

**Comment by Greg36** [comment]
Ok thanks, It was strange to me too.
