### ISSUE TITLE
Hud do not work in 2.0.4 

### ISSUE THREAD

**Issue by Greg36** [H4vC/PoeHud#72]
Sadly in 2.0.4 nothing is displaying for me, there is no menu or other parts of functionality.

You probably know this already, hopefully it is not a big issue.

I'm looking forward to the news. And again, thank you for your work!

**Comment by ghost** [comment]
I'm at work right now and i can't check it...but if there was something changed with 2.0.4...yes, it's possible not to work. Let's just wait for an update from the guys with memory addresses.

**Comment by H4vC** [comment]
Pushed the updates all is well now.
@vmv should I do a pull on your repo with the offset patched so that you can merge it and people can DL version of the hud ?

**Comment by ghost** [comment]
Sure, why not...there shouldn't be any problems...or just small one :DDD

**Comment by H4vC** [comment]
it's literally only the isInGame offset that changed.

**Comment by doomnezau** [comment]
It works man. H4vC version it's working right now and seems responsive.

**Comment by ghost** [comment]
Updated vmv version.

**Comment by Greg36** [comment]
All working perfectly for me now. Huge thanks to you :+1:
