### ISSUE TITLE
Is .Net framework 4.6 real mandatory?

### ISSUE THREAD

**Issue by TomTer** [H4vC/PoeHud#77]
Hello!

Just wanted to ask is .Net framework v4.6 real mandatory? For example it is not possible to install v4.6 on tiny Windows 7 versions (they are usually used in VM).

Best regards

**Comment by H4vC** [comment]
They are necessary for healthbars if you disable healthbars in the config you should be good to go.
Because we use 4.6 instructions to draw them.

**Comment by ghost** [comment]
Windows 7 is much worse then win 8.1. Why would you keep it. Also, win 8.1 it's consuming less then 7 in resources..all of them. Go on and install win 8.1.
