### ISSUE TITLE
Still crashing.

### ISSUE THREAD

**Issue by ElixirInteractive** [H4vC/PoeHud#79]
Re-downloaded the hud and all..

heres the "error"  message.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.TypeLoadException: Could not load type 'System.Numerics.Matrix4x4' from assembly 'System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at PoeHUD.Poe.RemoteMemoryObjects.Camera.WorldToScreen(Vector3 vec3, EntityWrapper entityWrapper)
   at PoeHUD.Hud.Health.HealthBarPlugin.Render()
   at PoeHUD.Hud.ExternalOverlay.<>c.<OnRender>b__21_0(IPlugin x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PoeHUD.Hud.ExternalOverlay.OnRender()
   at PoeHUD.Framework.Helpers.ActionHelper.SafeInvoke(Action action)
   at PoeHUD.Hud.UI.Graphics.RenderLoop()
   at PoeHUD.Hud.ExternalOverlay.<OnLoad>b__20_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoeHUD.Hud.ExternalOverlay.<OnLoad>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

PoeHUD
    Assembly Version: 6.3.9600.0
    Win32 Version: 6.3.9600.0
##     CodeBase: file:///C:/Users/Wyrelade/Desktop/poe%20hud%202/quEU1qR.exe

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

Tools
    Assembly Version: 0.0.0.0
    Win32 Version: 6.3.9600.0
##     CodeBase: file:///C:/Users/Wyrelade/Desktop/poe%20hud%202/quEU1qR.exe

SharpDX.Desktop
    Assembly Version: 3.0.0.0
    Win32 Version: 6.3.9600.0
##     CodeBase: file:///C:/Users/Wyrelade/Desktop/poe%20hud%202/quEU1qR.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

FSharp.Core
    Assembly Version: 4.3.0.0
    Win32 Version: 6.3.9600.0
##     CodeBase: file:///C:/Users/Wyrelade/Desktop/poe%20hud%202/quEU1qR.exe

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 6.3.9600.0
##     CodeBase: file:///C:/Users/Wyrelade/Desktop/poe%20hud%202/quEU1qR.exe

SharpDX.Mathematics
    Assembly Version: 3.0.0.0
    Win32 Version: 6.3.9600.0
##     CodeBase: file:///C:/Users/Wyrelade/Desktop/poe%20hud%202/quEU1qR.exe

System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll

System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

SharpDX
    Assembly Version: 3.0.0.0
    Win32 Version: 6.3.9600.0
##     CodeBase: file:///C:/Users/Wyrelade/Desktop/poe%20hud%202/quEU1qR.exe

SharpDX.Direct3D9
    Assembly Version: 3.0.0.0
    Win32 Version: 6.3.9600.0
##     CodeBase: file:///C:/Users/Wyrelade/Desktop/poe%20hud%202/quEU1qR.exe

System.Threading
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Threading/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.dll

System.Collections
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll

System.Runtime.InteropServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.dll

PoeFilterParser
    Assembly Version: 1.0.0.0
    Win32 Version: 6.3.9600.0
##     CodeBase: file:///C:/Users/Wyrelade/Desktop/poe%20hud%202/quEU1qR.exe

Antlr4.Runtime
    Assembly Version: 4.5.0.0
    Win32 Version: 6.3.9600.0
##     CodeBase: file:///C:/Users/Wyrelade/Desktop/poe%20hud%202/quEU1qR.exe

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by ghost** [comment]
You need Microsoft .NET Framework 4.6.
https://www.microsoft.com/en-us/download/details.aspx?id=48130

If you can't use 4.6, just disable Healhtbars.

**Comment by H4vC** [comment]
see above
