### ISSUE TITLE
Messed up preload alerts code

### ISSUE THREAD

**Issue by hunkiller** [H4vC/PoeHud#80]
After merge from vmv, I noticed some incorrect definitions in preload_alerts.txt, also some of the definitions have been moved to the source code which now looks messy. Why is it so? Revert that please.

**Comment by H4vC** [comment]
he has hard-coded the colours for them I'm working on a compromise that will let us have his nice colours and self defined preload alerts.

**Comment by H4vC** [comment]
It'll be fixed in the next major version till then you can just revert to a previous build since Github stores those.
