### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by ScottNorton** [H4vC/PoeHud#81]
As noted in the readme, PoeHUD does not work in fullscreen mode.
Will anything be done in the future to see if there's a remedy for this?

**Comment by ghost** [comment]
I don't think it's possible. That would be write to memory, highly detectable and hard to do. Think of this like 2 canvas, 1 with transparent background and the hud on it and the second one is the game. This is how it's working...one over another...if i'm not mistaken.
Use windowed fullscreen instead.

**Comment by H4vC** [comment]
Sadly impossible without either doing some pretty shady stuff with the GPU/DX or making poehud internal which neither of which are in the scope of this project.
