### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by wondadd** [H4vC/PoeHud#90]
Hello, the program is not recognizing area corrupted?

**Comment by ghost** [comment]
The method has changed to reduce the amount of info from preload area...If there is a corrupted area, the area name title will change to predefined corrupted color. Default is Color Crimson. You can change it anytime to get use to that...but the default looks nice. Check the forum btw,.

**Comment by wondadd** [comment]
Thanks for the answer. It's what I was looking for an area of more than 1 hour and was not finding.
