### ISSUE TITLE
Still crashes after fresh install

### ISSUE THREAD

**Issue by BobStoops** [H4vC/PoeHud#94]
Details

.NET Framework 4.6 or a later update is already installed on this computer.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
at PoeHUD.Hud.Loot.PoeFilterVisitor.VisitMain(MainContext context)
at PoeFilterParser.Model.PoeFilterParser.MainContext.Accept[TResult](IParseTreeVisitor`1 visitor)
at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
at PoeHUD.Hud.Loot.ItemAlertPlugin.OnEntityAdded(EntityWrapper entity)
at System.Action`1.Invoke(T obj)
at PoeHUD.Models.EntityListWrapper.RefreshState()
at PoeHUD.Controllers.GameController.RefreshState()
at PoeHUD.Hud.ExternalOverlay.OnRender()
at PoeHUD.Framework.Helpers.ActionHelper.SafeInvoke(Action action)
at PoeHUD.Hud.UI.Graphics.RenderLoop()
at PoeHUD.Hud.ExternalOverlay.<OnLoad>b__14_0()
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotificat ion(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at PoeHUD.Hud.ExternalOverlay.<OnLoad>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Ob ject state)

*************\* Loaded Assemblies **************
mscorlib
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1063.1 built by: NETFXREL3STAGE
## CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

PoeHUD
Assembly Version: 6.3.9600.0
Win32 Version: 6.3.9600.0
## CodeBase: file:///C:/Users/Doug/Downloads/POE_PROGRAMS/BoVbQ.exe

System
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2
## CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

Tools
Assembly Version: 0.0.0.0
Win32 Version: 6.3.9600.0
## CodeBase: file:///C:/Users/Doug/Downloads/POE_PROGRAMS/BoVbQ.exe

SharpDX.Desktop
Assembly Version: 3.0.0.0
Win32 Version: 6.3.9600.0
## CodeBase: file:///C:/Users/Doug/Downloads/POE_PROGRAMS/BoVbQ.exe

System.Windows.Forms
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2
## CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2
## CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

FSharp.Core
Assembly Version: 4.4.0.0
Win32 Version: 4.40.22810.0
## CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/FSharp.Core/v4.0_4.4.0.0__b03f5f7f11d50a3a/FSharp.Core.dll

System.Core
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2
## CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

Newtonsoft.Json
Assembly Version: 7.0.0.0
Win32 Version: 6.3.9600.0
## CodeBase: file:///C:/Users/Doug/Downloads/POE_PROGRAMS/BoVbQ.exe

SharpDX.Mathematics
Assembly Version: 3.0.0.0
Win32 Version: 6.3.9600.0
## CodeBase: file:///C:/Users/Doug/Downloads/POE_PROGRAMS/BoVbQ.exe

System.Runtime
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0
## CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll

System.Numerics
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2
## CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

System.Runtime.Serialization
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2
## CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Xml.Linq
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2
## CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

System.Xml
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2
## CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Data
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2
## CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

SharpDX
Assembly Version: 3.0.0.0
Win32 Version: 6.3.9600.0
## CodeBase: file:///C:/Users/Doug/Downloads/POE_PROGRAMS/BoVbQ.exe

SharpDX.Direct3D9
Assembly Version: 3.0.0.0
Win32 Version: 6.3.9600.0
## CodeBase: file:///C:/Users/Doug/Downloads/POE_PROGRAMS/BoVbQ.exe

System.Threading
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0
## CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.dll

System.Collections
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0
## CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll

System.Runtime.InteropServices
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0
## CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.dll

PoeFilterParser
Assembly Version: 1.0.0.0
Win32 Version: 6.3.9600.0
## CodeBase: file:///C:/Users/Doug/Downloads/POE_PROGRAMS/BoVbQ.exe

Antlr4.Runtime
Assembly Version: 4.5.0.0
Win32 Version: 6.3.9600.0
## CodeBase: file:///C:/Users/Doug/Downloads/POE_PROGRAMS/BoVbQ.exe

Accessibility
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2
## CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

System.Runtime.Extensions
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0
## CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Extensions.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
<system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

Made sure that I had the follwing:  Details

.NET Framework 4.6 or a later update is already installed on this computer.

I have downloaded latest version, reinstalled, and still get the above issue within 1 minute sometimes earlier when running the program.  Thanks.

**Comment by H4vC** [comment]
I do not support this any more as I don't play the game.
