### ISSUE TITLE
I might be doing something wrong but it seems blank?

### ISSUE THREAD

**Issue by viper949** [H4vC/PoeHud#95]
posted this on a different poehud but maybe this is the most up to date copy?

Hello! i just discovered this about a month ago and used it for a couple days until it seemed to go blank. Am I doing something wrong or did the patches mess something up?

**Comment by TehCheat** [comment]
This version is horribly out of date.  Why would you even come here?

**Comment by viper949** [comment]
well if you can point me to the most up to date version that would be wonderful. unless that was other one i commented on. just let me know

**Comment by TehCheat** [comment]
You've already commented with the same problem on the most up to date one.
